[tarko_servers]
# Production server
production ansible_host=tarko-backend.tarko.in ansible_user=ubuntu ansible_port=22

# Staging server
staging ansible_host=192.168.29.112 ansible_user=divine ansible_port=22

[local]
pi ansible_host=192.168.29.112 ansible_user=divine ansible_port=22
macmini ansible_host=192.168.29.111 ansible_user=diviine ansible_port=22

[tarko_servers:vars]
ansible_python_interpreter=/usr/bin/python3
